export type ChurnSegment = { segment: string; value: string; customers: number; churned: number; churnRate: number; monthlyCharges: number; churnedMonthlyCharges: number; totalCharges: number; averageTenure: number };
export type ChurnLift = { decile: number; customers: number; churned: number; churnRate: number; lift: number };
export type ChurnFeature = { feature: string; weight: number; direction: string };
export type ChurnRiskRow = { customerId: string; contract: string; tenure: number; monthlyCharges: number; serviceDepth: number; riskScore: number; action: string };
export type ChurnModelMetrics = { trainRecords: number; validationRecords: number; testRecords: number; featureCount: number; baselineRate: number; threshold: number; accuracy: number; precision: number; recall: number; f1: number; rocAuc: number; truePositive: number; trueNegative: number; falsePositive: number; falseNegative: number };

// Generated by projects/customer-churn-analysis/scripts/process_churn.py
export const churnSegments: ChurnSegment[] = [
  { segment: "Contract", value: "Month-to-month", customers: 3875, churned: 1655, churnRate: 0.4271, monthlyCharges: 257294.15, churnedMonthlyCharges: 120847.1, totalCharges: 5305861.5, averageTenure: 18.0 },
  { segment: "Contract", value: "One year", customers: 1473, churned: 166, churnRate: 0.1127, monthlyCharges: 95816.6, churnedMonthlyCharges: 14118.45, totalCharges: 4467053.5, averageTenure: 42.0 },
  { segment: "Contract", value: "Two year", customers: 1695, churned: 48, churnRate: 0.02832, monthlyCharges: 103005.85, churnedMonthlyCharges: 4165.3, totalCharges: 6283253.7, averageTenure: 56.7 },
  { segment: "InternetService", value: "DSL", customers: 2421, churned: 459, churnRate: 0.18959, monthlyCharges: 140665.35, churnedMonthlyCharges: 22529.2, totalCharges: 5121410.85, averageTenure: 32.8 },
  { segment: "InternetService", value: "Fiber optic", customers: 3096, churned: 1297, churnRate: 0.41893, monthlyCharges: 283284.4, churnedMonthlyCharges: 114300.05, totalCharges: 9923622.95, averageTenure: 32.9 },
  { segment: "InternetService", value: "No", customers: 1526, churned: 113, churnRate: 0.07405, monthlyCharges: 32166.85, churnedMonthlyCharges: 2301.6, totalCharges: 1011134.9, averageTenure: 30.5 },
  { segment: "PaymentMethod", value: "Bank transfer (automatic)", customers: 1544, churned: 258, churnRate: 0.1671, monthlyCharges: 103745.45, churnedMonthlyCharges: 20091.9, totalCharges: 4748279.9, averageTenure: 43.7 },
  { segment: "PaymentMethod", value: "Credit card (automatic)", customers: 1522, churned: 232, churnRate: 0.15243, monthlyCharges: 101231.85, churnedMonthlyCharges: 17946.6, totalCharges: 4671593.35, averageTenure: 43.3 },
  { segment: "PaymentMethod", value: "Electronic check", customers: 2365, churned: 1071, churnRate: 0.45285, monthlyCharges: 180345.0, churnedMonthlyCharges: 84288.75, totalCharges: 4944903.25, averageTenure: 25.2 },
  { segment: "PaymentMethod", value: "Mailed check", customers: 1612, churned: 308, churnRate: 0.19107, monthlyCharges: 70794.3, churnedMonthlyCharges: 16803.6, totalCharges: 1691392.2, averageTenure: 21.8 },
  { segment: "monthly_charge_band", value: "$40\u201379", customers: 2529, churned: 746, churnRate: 0.29498, monthlyCharges: 158830.9, churnedMonthlyCharges: 48118.3, totalCharges: 4197570.8, averageTenure: 26.2 },
  { segment: "monthly_charge_band", value: "$80+", customers: 2677, churned: 910, churnRate: 0.33993, monthlyCharges: 255280.85, churnedMonthlyCharges: 85669.35, totalCharges: 10642073.05, averageTenure: 40.8 },
  { segment: "monthly_charge_band", value: "Under $40", customers: 1837, churned: 213, churnRate: 0.11595, monthlyCharges: 42004.85, churnedMonthlyCharges: 5343.2, totalCharges: 1216524.85, averageTenure: 28.7 },
  { segment: "service_depth_band", value: "High depth (6+)", customers: 2187, churned: 444, churnRate: 0.20302, monthlyCharges: 202705.85, churnedMonthlyCharges: 43992.85, totalCharges: 10227478.9, averageTenure: 50.1 },
  { segment: "service_depth_band", value: "Low depth (0\u20132)", customers: 2123, churned: 404, churnRate: 0.1903, monthlyCharges: 61697.95, churnedMonthlyCharges: 17540.0, totalCharges: 1282042.8, averageTenure: 24.7 },
  { segment: "service_depth_band", value: "Medium depth (3\u20135)", customers: 2733, churned: 1021, churnRate: 0.37358, monthlyCharges: 191712.8, churnedMonthlyCharges: 77598.0, totalCharges: 4546647.0, averageTenure: 24.2 },
  { segment: "tenure_band", value: "0\u20136 months", customers: 1481, churned: 784, churnRate: 0.52937, monthlyCharges: 81067.95, churnedMonthlyCharges: 49896.1, totalCharges: 211146.9, averageTenure: 2.5 },
  { segment: "tenure_band", value: "13\u201324 months", customers: 1024, churned: 294, churnRate: 0.28711, monthlyCharges: 62829.85, churnedMonthlyCharges: 23081.65, totalCharges: 1153287.7, averageTenure: 18.4 },
  { segment: "tenure_band", value: "25\u201348 months", customers: 1594, churned: 325, churnRate: 0.20389, monthlyCharges: 105093.3, churnedMonthlyCharges: 27462.5, totalCharges: 3810380.35, averageTenure: 36.2 },
  { segment: "tenure_band", value: "49+ months", customers: 2239, churned: 213, churnRate: 0.09513, monthlyCharges: 165563.7, churnedMonthlyCharges: 19632.45, totalCharges: 10490848.75, averageTenure: 63.0 },
  { segment: "tenure_band", value: "7\u201312 months", customers: 705, churned: 253, churnRate: 0.35887, monthlyCharges: 41561.8, churnedMonthlyCharges: 19058.15, totalCharges: 390505.0, averageTenure: 9.4 },
];
export const churnModelMetrics: ChurnModelMetrics = { trainRecords: 4930, validationRecords: 704, testRecords: 1409, featureCount: 46, baselineRate: 0.23847, threshold: 0.35, accuracy: 0.7665, precision: 0.50737, recall: 0.71726, f1: 0.59433, rocAuc: 0.8197, truePositive: 241, trueNegative: 839, falsePositive: 234, falseNegative: 95 };
export const churnLiftByDecile: ChurnLift[] = [
  { decile: 1, customers: 140, churned: 95, churnRate: 0.67857, lift: 2.84556 },
  { decile: 2, customers: 141, churned: 75, churnRate: 0.53191, lift: 2.23056 },
  { decile: 3, customers: 141, churned: 60, churnRate: 0.42553, lift: 1.78445 },
  { decile: 4, customers: 141, churned: 31, churnRate: 0.21986, lift: 0.92196 },
  { decile: 5, customers: 141, churned: 21, churnRate: 0.14894, lift: 0.62456 },
  { decile: 6, customers: 141, churned: 20, churnRate: 0.14184, lift: 0.59482 },
  { decile: 7, customers: 141, churned: 18, churnRate: 0.12766, lift: 0.53533 },
  { decile: 8, customers: 141, churned: 8, churnRate: 0.05674, lift: 0.23793 },
  { decile: 9, customers: 141, churned: 5, churnRate: 0.03546, lift: 0.1487 },
  { decile: 10, customers: 141, churned: 3, churnRate: 0.02128, lift: 0.08922 },
];
export const churnFeatureWeights: ChurnFeature[] = [
  { feature: "tenure", weight: -0.33543, direction: "negative" },
  { feature: "MonthlyCharges", weight: 0.21891, direction: "positive" },
  { feature: "TotalCharges", weight: -0.18088, direction: "negative" },
  { feature: "PaperlessBilling=No", weight: -0.17326, direction: "negative" },
  { feature: "Contract=Two year", weight: -0.16641, direction: "negative" },
  { feature: "PhoneService=Yes", weight: -0.15584, direction: "negative" },
  { feature: "InternetService=DSL", weight: -0.15092, direction: "negative" },
  { feature: "Partner=Yes", weight: -0.14943, direction: "negative" },
];
export const churnRiskQueue: ChurnRiskRow[] = [
  { customerId: "2545-EBUPK", contract: "Month-to-month", tenure: 2, monthlyCharges: 84.05, serviceDepth: 4, riskScore: 0.7107, action: "Early-tenure onboarding" },
  { customerId: "4988-IQIGL", contract: "Month-to-month", tenure: 1, monthlyCharges: 75.35, serviceDepth: 3, riskScore: 0.6975, action: "Early-tenure onboarding" },
  { customerId: "4826-XTSOH", contract: "Month-to-month", tenure: 1, monthlyCharges: 86.05, serviceDepth: 4, riskScore: 0.6899, action: "Early-tenure onboarding" },
  { customerId: "1197-BVMVG", contract: "Month-to-month", tenure: 4, monthlyCharges: 74.45, serviceDepth: 3, riskScore: 0.6867, action: "Early-tenure onboarding" },
  { customerId: "1273-MTETI", contract: "Month-to-month", tenure: 4, monthlyCharges: 88.85, serviceDepth: 5, riskScore: 0.6848, action: "Early-tenure onboarding" },
  { customerId: "9231-ZJYAM", contract: "Month-to-month", tenure: 4, monthlyCharges: 78.85, serviceDepth: 3, riskScore: 0.6792, action: "Early-tenure onboarding" },
  { customerId: "8644-XLFBW", contract: "Month-to-month", tenure: 1, monthlyCharges: 71.65, serviceDepth: 2, riskScore: 0.6775, action: "Early-tenure onboarding" },
  { customerId: "9603-OAIHC", contract: "Month-to-month", tenure: 1, monthlyCharges: 70.05, serviceDepth: 2, riskScore: 0.675, action: "Early-tenure onboarding" },
  { customerId: "4342-HENTK", contract: "Month-to-month", tenure: 2, monthlyCharges: 70.65, serviceDepth: 2, riskScore: 0.6749, action: "Early-tenure onboarding" },
  { customerId: "5276-KQWHG", contract: "Month-to-month", tenure: 2, monthlyCharges: 69.6, serviceDepth: 2, riskScore: 0.6734, action: "Early-tenure onboarding" },
];
