export type ModelMetrics = {
  trainRecords: number;
  validationRecords: number;
  testRecords: number;
  featureCount: number;
  baselineRate: number;
  threshold: number;
  accuracy: number;
  precision: number;
  recall: number;
  f1: number;
  rocAuc: number;
  truePositive: number;
  trueNegative: number;
  falsePositive: number;
  falseNegative: number;
};

export type LiftRow = { decile: number; records: number; subscriptions: number; conversionRate: number; lift: number };
export type FeatureWeight = { feature: string; weight: number; direction: string };

// Generated by projects/bank-marketing-campaign/scripts/model_pipeline.py
export const modelMetrics: ModelMetrics = { trainRecords: 31647, validationRecords: 4521, testRecords: 9043, featureCount: 50, baselineRate: 0.11854, threshold: 0.2, accuracy: 0.84341, precision: 0.32766, recall: 0.30504, f1: 0.31594, rocAuc: 0.69035, truePositive: 327, trueNegative: 7300, falsePositive: 671, falseNegative: 745 };
export const liftByDecile: LiftRow[] = [
  { decile: 1, records: 904, subscriptions: 313, conversionRate: 0.34624, lift: 2.92075 },
  { decile: 2, records: 904, subscriptions: 114, conversionRate: 0.12611, lift: 1.06379 },
  { decile: 3, records: 904, subscriptions: 144, conversionRate: 0.15929, lift: 1.34373 },
  { decile: 4, records: 905, subscriptions: 119, conversionRate: 0.13149, lift: 1.10922 },
  { decile: 5, records: 904, subscriptions: 93, conversionRate: 0.10288, lift: 0.86783 },
  { decile: 6, records: 904, subscriptions: 78, conversionRate: 0.08628, lift: 0.72785 },
  { decile: 7, records: 905, subscriptions: 72, conversionRate: 0.07956, lift: 0.67112 },
  { decile: 8, records: 904, subscriptions: 48, conversionRate: 0.0531, lift: 0.44791 },
  { decile: 9, records: 904, subscriptions: 57, conversionRate: 0.06305, lift: 0.53189 },
  { decile: 10, records: 905, subscriptions: 34, conversionRate: 0.03757, lift: 0.31692 },
];
export const topFeatureWeights: FeatureWeight[] = [
  { feature: "default=no", weight: -0.33617, direction: "negative" },
  { feature: "poutcome=unknown", weight: -0.32937, direction: "negative" },
  { feature: "housing=yes", weight: -0.27294, direction: "negative" },
  { feature: "loan=no", weight: -0.25198, direction: "negative" },
  { feature: "marital=married", weight: -0.23101, direction: "negative" },
  { feature: "education=secondary", weight: -0.18807, direction: "negative" },
  { feature: "contact=unknown", weight: -0.17757, direction: "negative" },
  { feature: "month=may", weight: -0.15966, direction: "negative" },
];
export const modelFeatureCount = 50;
